---
# tasks file for commmon_fish
- name: Defaut package manager
  debug: var=ansible_pkg_mgr

- name: Try fish command
  command: fish
  register: is_fish_existed
  changed_when: False
  ignore_errors: yes

- name: Is fish existed?
  debug:
    msg: "Return code is {{ is_fish_existed }} "

- name: Start install fish on selected OS
  include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: is_fish_existed.rc > 0

- name: Start install fish on MacOs (Homebrew)
  include_tasks: MacOs.yml
  when: ansible_pkg_mgr == "homebrew"

- name: Where is fish
  command: which fish
  register: fish_location
  when: fish_as_default_shell
  changed_when: False

- name: Change user default shell to fish
  user:
    name: ansible_user_id
    shell: "{{ fish_location.stdout }}"
  when: fish_as_default_shell
